<a href="https://colab.research.google.com/github/SanuraagM/Improved-K-Means-/blob/main/Improved_K_Means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [184]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

In [185]:
from google.colab import files
uploaded = files.upload()

Saving Clustering.csv to Clustering (4).csv


In [186]:
import io 
df = pd.read_csv(io.BytesIO(uploaded['Clustering.csv']))

In [187]:
df

x          y
0    3.367596   3.536694
1    2.667870   4.479919
2    1.344171   3.282591
3    1.389414   4.683227
4    1.644644   4.320822
..        ...        ...
185  8.610144  10.429247
186  6.775686  11.724382
187  7.023465   9.632056
188  6.115584   9.449803
189  7.868889  12.894445

[190 rows x 2 columns]

In [188]:
df.dtypes
n = df.shape[0]
dfarr = df.values

In [189]:
def dist(x1,x2,y1,y2):
   p1=x1-x2
   p2=y1-y2
   n=p1**2+p2**2
   d=np.sqrt(n)
   return(d)


In [190]:
def find_value_location(arr, value):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
            if arr[i][j] == value:
                return (j)

In [191]:
K=2
cluster_center = np.empty((K, 2), dtype=float)
for i in range (K) :
  random_row = df.sample()  
  cluster_center[i]=random_row #Assigning a random row from the dataframe as cluster center
print(cluster_center)

[[ 2.08341671  1.92917586]
 [ 7.975533   10.79934974]]


In [192]:
  
  d = np.empty((n, K), dtype=float)
  for i in range (n):
    d[i][0]=dist(cluster_center[0][0],dfarr[i][0],cluster_center[0][1],dfarr[i][1]) #calculating distance of datapoints from clustercenters
    d[i][1]=dist(cluster_center[1][0],dfarr[i][0],cluster_center[1][1],dfarr[i][1])


  Cluster1x = []
  Cluster1y = []
  Cluster2x = []
  Cluster2y = []

  for i in range (n):
    j=find_value_location(d, min(d[i]))
    if (j==0):
      Cluster1x=np.append(Cluster1x,dfarr[i][0]) # Assigning the clusters with datapoints x coordinate
      Cluster1y=np.append(Cluster1y,dfarr[i][1]) # Assigning the clusters with datapoints y coordinate
    elif (j==1):
      Cluster2x=np.append(Cluster2x,dfarr[i][0])
      Cluster2y=np.append(Cluster2y,dfarr[i][1])

  print(Cluster1x.shape) # identifying the number of points in each cluster
  print(Cluster2x.shape)
  print(cluster_center)
  a=Cluster1x.shape
  cluster_center[0][0]=np.mean(Cluster1x) # Updating the cluster centers
  cluster_center[0][1]=np.mean(Cluster1y)
  cluster_center[1][0]=np.mean(Cluster2x)
  cluster_center[1][1]=np.mean(Cluster2y)

  


(101,)
(89,)
[[ 2.08341671  1.92917586]
 [ 7.975533   10.79934974]]


In [193]:
new_d = np.empty((n,K), dtype=float)
for i in range (n):
  new_d[i][0]=dist(cluster_center[0][0],dfarr[i][0],cluster_center[0][1],dfarr[i][1]) #calculating the new distance of datapoints from clustercenters
  new_d[i][1]=dist(cluster_center[1][0],dfarr[i][0],cluster_center[1][1],dfarr[i][1])

In [197]:
a=0
while (True):
  for i in range(n):
    J=find_value_location(d, min(d[i]))
    if new_d[i][J]>d[i][J]:                          #Comparing the new and previous distance of each points from cluster center
      j=find_value_location(new_d, min(new_d[i]))    
      if j!=J :
        if (j==0):
          Cluster1x=np.append(Cluster1x,dfarr[i][0]) # Updating the cluster1 with datapoints x coordinate
          Cluster1y=np.append(Cluster1y,dfarr[i][1]) # Updating the cluster1 with datapoints y coordinate
          rows_to_remove = Cluster2x == dfarr[i][0]
          Cluster2x = Cluster2x[~rows_to_remove]
          rows_to_remove = Cluster2y == dfarr[i][1]
          Cluster2y = Cluster2y[~rows_to_remove]
        elif (j==1):
          Cluster2x=np.append(Cluster2x,dfarr[i][0]) # Updating the cluster2 with datapoints x coordinate
          Cluster2y=np.append(Cluster2y,dfarr[i][1]) # Updating the cluster2 with datapoints y coordinate
          rows_to_remove = Cluster1x == dfarr[i][0]
          Cluster1x = Cluster1x[~rows_to_remove]
          rows_to_remove = Cluster1y == dfarr[i][1]
          Cluster1y = Cluster1y[~rows_to_remove]
  
  print(Cluster1x.shape) # identifying the number of points in each cluster
  print(Cluster2x.shape)
  print(cluster_center)
  
  cluster_center[0][0]=np.mean(Cluster1x) # Updating the cluster centers
  cluster_center[0][1]=np.mean(Cluster1y)
  cluster_center[1][0]=np.mean(Cluster2x)
  cluster_center[1][1]=np.mean(Cluster2y)
  if(cluster_center[0][0]==a):
    break
  a=np.mean(Cluster1x)
  d=new_d

(101,)
(89,)
[[1.8295627  3.15937099]
 [8.00295205 9.96079954]]
(101,)
(89,)
[[1.8295627  3.15937099]
 [8.00295205 9.96079954]]


In [195]:
  d = np.empty((n, K), dtype=float)
  for i in range (n):
    d[i][0]=dist(cluster_center[0][0],dfarr[i][0],cluster_center[0][1],dfarr[i][1]) #calculating distance of datapoints from clustercenters
    d[i][1]=dist(cluster_center[1][0],dfarr[i][0],cluster_center[1][1],dfarr[i][1])

In [196]:
Cluster1=[]
Cluster2=[]
for i in range(n):

  j=find_value_location(d,min(d[i]))
  if (j==0):
    Cluster1.append(df.iloc[i].tolist())
  elif (j==1):
    Cluster2.append(df.iloc[i].tolist())
print(Cluster1)
print(Cluster2)

[[3.367595992, 3.536693976], [2.667869766, 4.479918773], [1.34417121, 3.28259119], [1.389413781, 4.683226649], [1.644643839, 4.320822372], [0.776027424, 2.653666763], [3.264101412, 3.692761955], [-0.182646569, 2.592825707], [1.138215029, 2.800296375], [0.759164489, 4.648057452], [2.164526614, 3.355084546], [-0.093799022, 3.406345086], [1.748728207, 2.318376112], [2.077867213, 5.316457862], [2.456727403, 1.825483626], [0.614715125, 3.242371429], [2.8111124, 1.929037857], [2.719377151, 2.392575984], [1.912883969, 4.536237226], [3.231670986, 3.012060236], [1.463657172, 1.74325882], [2.019935554, 2.228683192], [2.524658209, 3.677928919], [2.547609253, 2.232318462], [1.029465626, 1.436641809], [3.502668811, 4.020180816], [1.701383352, 2.060109896], [1.351904811, 3.51179265], [0.226915793, 2.277328401], [1.499936663, 2.959304954], [2.521173676, 3.282199335], [2.237783894, 0.837199144], [1.999744589, 3.420673734], [2.628220717, 3.886863115], [3.583228512, 3.962464196], [1.275954144, 3.4247583